language: node_js
node_js:
- '14'
services:
- mongodb
- mysql
- postgresql
sudo: false
cache:
  directories:
  - node_modules
before_script:
  # install MySQL 8
- wget https://repo.mysql.com//mysql-apt-config_0.8.10-1_all.deb
- sudo dpkg -i mysql-apt-config_0.8.10-1_all.deb
- sudo apt-get update -q
- sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server
- sudo systemctl restart mysql
- sudo mysql_upgrade

- mysql -e 'CREATE DATABASE IF NOT EXISTS `default`;'
- npm install
- npm run bootstrap
- npm run build
- sleep 1
script:
- npm run test
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
- cd packages/orm-integration && npm run test && cd -
- cd packages/benchmark; npm run setup && npm run benchmark && cd -
