language: node_js
node_js:
- '14'
services:
- mongodb
- mysql
- postgresql
sudo: false
cache:
  directories:
  - node_modules
before_script:
- mysql -e 'CREATE DATABASE IF NOT EXISTS default;'
- npm install
- npm run bootstrap
- npm run tsc
- sleep 1
script:
- npm run test
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
- cd packages/benchmark; npm run setup && npm run benchmark
