language: node_js
node_js:
- '14'
services:
- mongodb
- mysql
- postgresql
sudo: false
cache:
  directories:
  - node_modules
before_script:
- npm install
- ./node_modules/.bin/lerna bootstrap --nohoist \* --no-ci
- ./node_modules/.bin/tsc --version
- sleep 1
script:
- ./node_modules/.bin/tsc --build
- ./node_modules/.bin/jest --coverage --forceExit
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
- cd packages/benchmark; npm run setup && npm run benchmark
