name: CI

on: push

jobs:
  build:
    runs-on: [ ubuntu-20.04 ]

    strategy:
      matrix:
        node-version: [ 14.x ]
        mongodb-version: [ 4.2 ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache ~/.npm
        uses: actions/cache@v1
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Setup
        run: |
          node --version
          npm install

      - name: Lerna bootstrap
        run: npm run bootstrap

      - name: Build
        run: npm run build

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '8.0'
          mysql database: 'default'
          mysql root password: 'root'

      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '10'

      - name: Test
        run: npm run test
        env:
          MYSQL_PW: root
